/**
 * One source of truth for the values that appear in more than one place.
 *
 * The canonical URL and the preview image are absolute, not relative: Open Graph
 * consumers fetch `og:image` out of band, with no page as context to resolve
 * against, so a relative path renders as a broken card on every platform. Keeping
 * the origin here rather than reading it off the request means a preview is never
 * generated for a Preview deployment and then shared as if it were production.
 */

export const SITE_NAME = 'Sheet2JSON'

/** The one origin this site is canonical at. */
export const SITE_URL = 'https://sheet2json.vercel.app'

/**
 * The preview card, regenerated by `bun run og:image`.
 *
 * 1200x630 is what every consumer asks for. The dimensions are declared in the
 * meta tags as well so a scraper can lay the card out without downloading it.
 */
export const OG_IMAGE = {
  url: `${SITE_URL}/og.png`,
  width: 1200,
  height: 630,
  alt: 'A Google Sheets table next to the same rows as JSON objects.',
}

export const SITE_DESCRIPTION =
  'Extract Google Sheets into structured JSON. Paste a link, or pull any sheet into your code with a REST API and your own API key.'

/**
 * The link preview every share renders.
 *
 * `summary_large_image` rather than `summary` because the card is 1200x630 and
 * the small card crops it down to a letterbox nobody can read.
 *
 * The Open Graph and Twitter values are deliberately the same strings. Two
 * copies of the same marketing copy drift apart the first time one is edited.
 */
export function socialMeta(title: string, description: string) {
  return [
    { property: 'og:site_name', content: SITE_NAME },
    { property: 'og:type', content: 'website' },
    { property: 'og:title', content: title },
    { property: 'og:description', content: description },
    { property: 'og:image', content: OG_IMAGE.url },
    { property: 'og:image:width', content: String(OG_IMAGE.width) },
    { property: 'og:image:height', content: String(OG_IMAGE.height) },
    { property: 'og:image:alt', content: OG_IMAGE.alt },
    { name: 'twitter:card', content: 'summary_large_image' },
    { name: 'twitter:title', content: title },
    { name: 'twitter:description', content: description },
    { name: 'twitter:image', content: OG_IMAGE.url },
    { name: 'twitter:image:alt', content: OG_IMAGE.alt },
  ]
}
